parserOptions:
  ecmaVersion: 6
env:
  node: true

parser: @typescript-eslint/parser


extends:
  - eslint:recommended
  - airbnb-base
  - airbnb-typescript/base

rules:
  no-console:
    - error
    - allow:
        - warn
        - error
