name: Slack Webhook

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  slack-notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: tokorom/action-slack-incoming-webhook@master
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        with:
          text: <https://github.com/mengasis/gatsby-monorepo/pull/${{ github.event.number }} | PR ${{ github.event.pull_request.number }}>
