name: Slack Webhook

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON:     ':oso-embonor:'
          SLACK_COLOR:    '#00b181'
          SLACK_MESSAGE:  'Rebase master now!! :ahhhhhhhhh: :rocket:'
          SLACK_TITLE:    ${{ github.event.number }} PR closed
          SLACK_USERNAME: Monorepo status
          MSG_MINIMAL:    true
